### ISSUE TITLE
test edit user himself fails on master

### ISSUE THREAD

**Issue by tpokorra** [TBits/KolabScripts#44]
./testCreateUserAndEditSelf.py KolabWAPCreateUserAndEditSelf.test_edit_user_himself

`/var/log/kolab/pykolab.log`:

```
2015-01-05 09:25:22,108 pykolab.auth ERROR An error occured using _paged_search: OperationalError('(OperationalError) attempt to write a readonly database',)
2015-01-05 09:25:22,109 pykolab.auth ERROR Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pykolab/auth/ldap/__init__.py", line 2769, in _search
    secondary_domains
  File "<string>", line 10, in <module>
  File "/usr/lib/python2.6/site-packages/pykolab/auth/ldap/__init__.py", line 2553, in _paged_search
    callback(entry=_result_data)
  File "/usr/lib/python2.6/site-packages/pykolab/auth/ldap/__init__.py", line 2376, in _synchronize_callback
    eval("self._change_none_%s(entry, None)" % (entry['type']))
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/pykolab/auth/ldap/__init__.py", line 1937, in _change_none_user
    cache.get_entry(self.domain, entry)
  File "/usr/lib/python2.6/site-packages/pykolab/auth/ldap/cache.py", line 150, in get_entry
    db.commit()
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/orm/session.py", line 719, in commit
    self.transaction.commit()
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/orm/session.py", line 352, in commit
    self._prepare_impl()
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/orm/session.py", line 332, in _prepare_impl
    self.session.flush()
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/orm/session.py", line 1814, in flush
    self._flush(objects)
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/orm/session.py", line 1896, in _flush
    flush_context.execute()
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/orm/unitofwork.py", line 525, in execute
    uow
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/orm/persistence.py", line 58, in save_obj
    mapper, table, update)
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/orm/persistence.py", line 491, in _emit_update_statements
    execute(statement, params)
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/engine/base.py", line 664, in execute
    params)
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/engine/base.py", line 764, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/engine/base.py", line 878, in _execute_context
    context)
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/engine/base.py", line 871, in _execute_context
    context)
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/engine/default.py", line 320, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) attempt to write a readonly database u'UPDATE entry SET last_change=? WHERE entry.id = ?' ('2015-01-05 08:22:10.000000', 2)
```

**Comment by tpokorra** [comment]
see also https://lists.kolab.org/pipermail/users/2014-October/018001.html

**Comment by tpokorra** [comment]
this is an sqlite database: https://git.kolab.org/pykolab/tree/pykolab/auth/ldap/cache.py#n176

**Comment by tpokorra** [comment]
```
ls -la  /var/lib/kolab/
insgesamt 28
drwxrwxr-x  2 kolab kolab-n 4096  5. Jan 09:25 .
drwxr-xr-x 30 root  root    4096  5. Jan 09:15 ..
-rw-r--r--  1 kolab kolab   5120  5. Jan 09:25 auth_cache.db
-rw-r--r--  1 root  root    2048  5. Jan 09:19 domain20150105091921.de.db
-rw-r--r--  1 kolab kolab   2048  5. Jan 09:22 domain20150105092206.de.db
-rw-r--r--  1 kolab kolab   2048  5. Jan 09:25 test.pokorra.de.db
```

**Comment by tpokorra** [comment]
after changing the ownership manually, I get now in `/var/log/kolab-webadmin/errors`:

    [05-Jan-2015 09:57:20] PHP Warning:  array_map(): Argument #2 should be an array in /usr/share/kolab-webadmin/lib/kolab_utils.php on line 183
    [05-Jan-2015 09:57:21] PHP Warning:  ldap_mod_replace(): Modify: Insufficient access in /usr/share/php/Net/LDAP3.php on line 2262

**Comment by tpokorra** [comment]
the readonly sqlite database is not the initial problem.
The actual problem is the LDAP Insufficient access problem. Perhaps related to https://github.com/tpokorra/pykolab/commit/cdfc34e7de1d8174d97d5ba2e1caf828a7f6bae7?

**Comment by tpokorra** [comment]
ldap search returns all attributes: https://github.com/tpokorra/kolab-wap/commit/d1f86621d0ffdbdb536fb352d9b3a74397aa04c2

**Comment by tpokorra** [comment]
filed a bug for the warning of array_map: https://issues.kolab.org/show_bug.cgi?id=4164

**Comment by tpokorra** [comment]
now looking at alias again: it seems we get from the UI only one alias for the user:

    [alias] => user20150105111313@test.pokorra.de

the alias of the user in LDAP has two values:

            [alias] => Array
                (
                    [0] => user20150105111313@test.pokorra.de
                    [1] => u.user20150105111313@test.pokorra.de
                )

in the UI, I can see both aliases as well.

**Comment by tpokorra** [comment]
somehow the other alias gets lost in the call of parse_input_attributes: http://git.kolab.org/kolab-wap/tree/lib/api/kolab_api_service_user.php#n132

**Comment by tpokorra** [comment]
filed https://issues.kolab.org/show_bug.cgi?id=4166
