### ISSUE TITLE
wallace error at end of reinstall.sh on Debian

### ISSUE THREAD

**Issue by tpokorra** [TBits/KolabScripts#45]
```
[ ok ] Reloading web server config: apache2 not running.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wallace/__init__.py", line 285, in do_wallace
    pair = s.accept()
  File "/usr/lib/python2.7/socket.py", line 202, in accept
```

**Comment by tpokorra** [comment]
this does not seem to happen anymore
