### ISSUE TITLE
tests: WebDriverException: Can not connect to GhostDriver

### ISSUE THREAD

**Issue by tpokorra** [TBits/KolabScripts#51]
This happens every now and again, for Debian and CentOS:

```
[01690] E
[01690] ======================================================================
[01690] ERROR: test_catch_all (__main__.KolabEmailCatchAll)
[01690] ----------------------------------------------------------------------
[01690] Traceback (most recent call last):
[01690]   File "./testEmailCatchAll.py", line 21, in setUp
[01690]     self.driver = self.kolabWAPhelper.init_driver()
[01690]   File "/root/lbs-kolab-test/kolab-test/KolabScripts-Kolab3.4/pySeleniumTests/helperKolabWAP.py", line 38, in init_driver
[01690]     self.driver = webdriver.PhantomJS('phantomjs', service_args=['--ignore-ssl-errors=true'])
[01690]   File "/usr/lib/python2.7/site-packages/selenium-2.45.0-py2.7.egg/selenium/webdriver/phantomjs/webdriver.py", line 50, in __init__
[01690]     self.service.start()
[01690]   File "/usr/lib/python2.7/site-packages/selenium-2.45.0-py2.7.egg/selenium/webdriver/phantomjs/service.py", line 81, in start
[01690]     raise WebDriverException("Can not connect to GhostDriver")
[01690] WebDriverException: Message: Can not connect to GhostDriver
```

**Comment by tpokorra** [comment]
see http://stackoverflow.com/questions/27691364/phantomjs-connect-to-ghostdriver-error and http://stackoverflow.com/questions/24578879/selenium-cant-connect-to-ghostdriver-but-only-sometimes

**Comment by tpokorra** [comment]
see also http://stackoverflow.com/questions/15067107/difference-between-webdriver-dispose-close-and-quit: should use driver.Quit rather than driver.Close

**Comment by tpokorra** [comment]
this has greatly improved with the change from driver.close to driver.quit
