### ISSUE TITLE
master: tests sometimes fail

### ISSUE THREAD

**Issue by tpokorra** [TBits/KolabScripts#54]
I get in `/var/log/kolab/pykolab.log`:

```
2015-05-29 11:45:08,462 pykolab.auth ERROR An error occured using _persistent_search: AttributeError("'LDAP' object has no attribute '_change_modify_None'",)
2015-05-29 11:45:08,463 pykolab.auth ERROR Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pykolab/auth/ldap/__init__.py", line 2887, in _search
    secondary_domains
  File "<string>", line 10, in <module>
  File "/usr/lib/python2.7/site-packages/pykolab/auth/ldap/__init__.py", line 2622, in _persistent_search
    secondary_domains=secondary_domains
  File "/usr/lib/python2.7/site-packages/pykolab/auth/ldap/__init__.py", line 2468, in _synchronize_callback
    entry['type']
  File "<string>", line 1, in <module>
AttributeError: 'LDAP' object has no attribute '_change_modify_None'
```

This looks a little bit like https://issues.kolab.org/show_bug.cgi?id=4218, which was fixed in https://cgit.kolab.org/pykolab/commit/?id=68f70786d666836d3b1d850da17d3646839cfd01

My error cannot reliably be reproduced

**Comment by tpokorra** [comment]
I have not seen this for a while anymore
