### ISSUE TITLE
tests fail with internal error

### ISSUE THREAD

**Issue by tpokorra** [TBits/KolabScripts#73]
on my nightly builds, I often get this error, though it cannot be reproduced easily:

```
[00:52:37] ======================================================================
[00:52:37] FAIL: test_edit_user_himself (__main__.KolabWAPCreateUserAndEditSelf)
[00:52:37] ----------------------------------------------------------------------
[00:52:37] Traceback (most recent call last):
[00:52:37]   File "./testCreateUserAndEditSelf.py", line 50, in test_edit_user_himself
[00:52:37]     self.helper_user_edits_himself()
[00:52:37]   File "./testCreateUserAndEditSelf.py", line 31, in helper_user_edits_himself
[00:52:37]     self.assertEquals("User updated successfully.", elem.text, "User was not saved successfully, message: " + elem.text)
[00:52:37] AssertionError: User was not saved successfully, message: Internal error
[00:52:37] 
[00:52:37] ======================================================================
[00:52:37] FAIL: test_edit_user_himself_multi_domain_with_quota (__main__.KolabWAPCreateUserAndEditSelf)
[00:52:37] ----------------------------------------------------------------------
[00:52:37] Traceback (most recent call last):
[00:52:37]   File "./testCreateUserAndEditSelf.py", line 70, in test_edit_user_himself_multi_domain_with_quota
[00:52:37]     self.helper_user_edits_himself()
[00:52:37]   File "./testCreateUserAndEditSelf.py", line 31, in helper_user_edits_himself
[00:52:37]     self.assertEquals("User updated successfully.", elem.text, "User was not saved successfully, message: " + elem.text)
[00:52:37] AssertionError: User was not saved successfully, message: Internal error
[00:52:37] 
[00:52:37] ----------------------------------------------------------------------
```

**Comment by tpokorra** [comment]
the error in /var/log/kolab-webadmin/errors:

```
[05-Aug-2016 08:14:49 Europe/Berlin] PHP Warning:  ldap_mod_del(): Modify: Insufficient access in /usr/share/php/Net/LDAP3.php on line 2340
[05-Aug-2016 08:15:48 Europe/Berlin] PHP Warning:  ldap_mod_del(): Modify: Insufficient access in /usr/share/php/Net/LDAP3.php on line 2340
```

**Comment by tpokorra** [comment]
works in vanilla mode, does not work after initMultiDomain, but works after a restart?

**Comment by tpokorra** [comment]
enabled debug_mode in kolab.conf

```
[kolab_wap]
debug_mode = TRACE
```

will see if that shows what ldap attribute causes the problem

**Comment by tpokorra** [comment]
```
[05-Aug-2016 10:40:21 +0200](tg3g7ecb4q7r198k0ihhka1p83): [WARNING] (api) LDAP: Failed to delete attributes on uid=user20160805103955,ou=People,dc=lbs,dc=solidcharity,dc=com: {"mailhost":["localhost"]}
```

**Comment by tpokorra** [comment]
just thinking: is mailhost set by kolabd? do I need to wait a little bit longer after creating the user? or force the sync?

**Comment by tpokorra** [comment]
that does not seem to work. just hangs on Kolab 3.4, and takes much longer for Winterfell and Kolab 16
