### ISSUE TITLE
test for LastLogin does not work anymore for Winterfell

### ISSUE THREAD

**Issue by tpokorra** [TBits/KolabScripts#83]
```
[00:38:20] ======================================================================
[00:38:20] ERROR: test_last_login (__main__.KolabWAPLastLogin)
[00:38:20] ----------------------------------------------------------------------
[00:38:20] Traceback (most recent call last):
[00:38:20]   File "./testLastLogin.py", line 35, in test_last_login
[00:38:20]     self.assertTrue(int(value) > 1388534400, "login date should be after 1 January 2014")
[00:38:20] TypeError: int() argument must be a string or a number, not 'NoneType'
[00:38:20] 
[00:38:20] ======================================================================
[00:38:20] ERROR: test_last_login_in_other_domain (__main__.KolabWAPLastLogin)
[00:38:20] ----------------------------------------------------------------------
[00:38:20] Traceback (most recent call last):
[00:38:20]   File "./testLastLogin.py", line 57, in test_last_login_in_other_domain
[00:38:20]     self.assertTrue(int(value) > 1388534400, "login date should be after 1 January 2014")
[00:38:20] TypeError: int() argument must be a string or a number, not 'NoneType'
[00:38:20] 
[00:38:20] ----------------------------------------------------------------------
[00:38:20] Ran 2 tests in 35.374s
[00:38:20] 
[00:38:20] FAILED (errors=2)
[00:38:20] 07:38:37 Running test: test_last_login
[00:38:20] 07:38:39 User is logged in to WAP: Directory Manager
[00:38:20] 07:38:46 User user20190313073840 has been created. Login with user20190313073840.user20190313073840@lbs.solidcharity.com and password Test1234!.
[00:38:20] 07:38:46 User has logged out from WAP
[00:38:20] 07:38:50 User is logged in to Roundcube: user20190313073840.user20190313073840@lbs.solidcharity.com
[00:38:20] 07:38:50 User has logged out from Roundcube
[00:38:20] 07:38:50 self.driver.page_source has been written to /tmp/output20190313073850.html
[00:38:20] 
[00:38:20] 07:38:52 Running test: test_last_login_in_other_domain
[00:38:20] 07:38:54 User is logged in to WAP: Directory Manager
[00:38:20] 07:38:57 Domain domain20190313073855.de has been created
[00:38:20] 07:38:58 Domain domain20190313073855.de has been selected
[00:38:20] 07:38:58 loading
[00:38:20] 07:39:06 User user20190313073859 has been created. Login with user20190313073859.user20190313073859@domain20190313073855.de and password Test1234!.
[00:38:20] 07:39:06 User has logged out from WAP
[00:38:20] 07:39:09 User is logged in to Roundcube: user20190313073859.user20190313073859@domain20190313073855.de
[00:38:20] 07:39:10 User has logged out from Roundcube
[00:38:20] 07:39:10 self.driver.page_source has been written to /tmp/output20190313073910.html
```

**Comment by tpokorra** [comment]
I think it is test_unique_id_across_domains, https://github.com/TBits/KolabScripts/blob/KolabWinterfell/pySeleniumTests/testUIDAcrossDomains.py#L23, enable_editable_uid(), which changes the settings of Kolab user type, and tbitskolabuser is not in the list of object classes, and therefore it gets removed.

**Comment by tpokorra** [comment]
list of object classes is compiled in `lib/api/kolab_api_service_form_value.php`, `function select_options_objectclass`, which calls `classes_allowed()` in `/usr/share/php/Net/LDAP3.php`.

that uses caching of the ldap scheme in init_schema, and that uses a path `/tmp/ldap:localhost:389-Net_LDAP2_Schema.cache` which is not reset in initTBitsISP.sh
