### ISSUE TITLE
Kolab16 test fails due to Postfix issues resolving the recipient name

### ISSUE THREAD

**Issue by tpokorra** [TBits/KolabScripts#84]
```
[00:21:34] ERROR: test_send_and_receive_email (__main__.KolabEmailSendAndReceiveEmail)
[00:21:34] ----------------------------------------------------------------------
[00:21:34] Traceback (most recent call last):
[00:21:34]   File "./testEmailSendAndReceive.py", line 32, in test_send_and_receive_email
[00:21:34]     kolabWAPhelper.logout_roundcube()
[00:21:34]   File "/root/KolabScripts-Kolab16/pySeleniumTests/helperKolabWAP.py", line 225, in logout_roundcube
[00:21:34]     self.wait_loading()
[00:21:34]   File "/root/KolabScripts-Kolab16/pySeleniumTests/helperKolabWAP.py", line 132, in wait_loading
[00:21:34]     alert = self.driver.switch_to_alert();
[00:21:34]   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 803, in switch_to_alert
[00:21:34]     return self._switch_to.alert
[00:21:34]   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/switch_to.py", line 55, in alert
[00:21:34]     alert.text
[00:21:34]   File "/usr/lib/python2.7/site-packages/selenium/webdriver/common/alert.py", line 67, in text
[00:21:34]     return self.driver.execute(Command.W3C_GET_ALERT_TEXT)["value"]
[00:21:34]   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
[00:21:34]     self.error_handler.check_response(response)
[00:21:34]   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
[00:21:34]     raise exception_class(message, screen, stacktrace)
[00:21:34] NoAlertPresentException: Message: no such alert
[00:21:34]   (Session info: headless chrome=79.0.3945.130)
```

in `/var/log/maillog`:

```
Apr  8 22:32:28 l005 postfix/submission/smtpd[2406]: connect from localhost[::1]
Apr  8 22:32:28 l005 postfix/submission/smtpd[2406]: NOQUEUE: reject: RCPT from localhost[::1]: 550 5.1.1 <user20200408222327.user20200408222327@build04lxd.lbs.solidcharity.com>: Recipient address rejected: User unknown in local recipient table; from=<user20200408222319.user20200408222319@build04lxd.lbs.solidcharity.com> to=<user20200408222327.user20200408222327@build04lxd.lbs.solidcharity.com> proto=ESMTP helo=<localhost>
Apr  8 22:32:28 l005 postfix/submission/smtpd[2406]: disconnect from localhost[::1]
```

I can reproduce that in the roundcube client, when I try to send an email from user1 to user2. The to field accepts the email, and can find the user. but when I send the email, I get the error as written to `/var/log/maillog`

**Comment by tpokorra** [comment]
this is because the hostname is l005.build04lxd.lbs.solidcharity.com, and the email domain name is build04lxd.lbs.solidcharity.com. that has 4 components, we only support 2 or 3 components for ldap recipient lookup
